<?php

namespace Ashan\CurrencyExchangeRate;

use Illuminate\Support\ServiceProvider;

class CurrencyExchangeRateServiceProvider extends ServiceProvider
{
    public function boot(){
        
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
